
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
secrets:
  - name: quay-alegrosdemos
imagePullSecrets:
  - name: quay-alegrosdemos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipelines-scc-clusterrole-custom
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-bot-pipeline-scc
  namespace: cicd-devsec-ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-scc-clusterrole
subjects:
- kind: ServiceAccount
  name: build-bot
  namespace: cicd-devsec-ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buid-bot-scc
  namespace: cicd-devsec-ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-scc-clusterrole-custom
subjects:
- kind: ServiceAccount
  name: build-bot
  namespace: cicd-devsec-ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-bot-edit
  namespace: cicd-devsec-ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: build-bot
  namespace: cicd-devsec-ops