apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: validated-pr
spec:
  stepTemplate:
    volumeMounts:
    - name: trusted-ca
      mountPath: /etc/pki/ca-trust/extracted/pem
      readOnly: true
  params:
  - name: git-repo-url
    type: string
    description: "Git Repository URL"
  - name: git-branch
    type: string
    description: "Git Branch to monitor"
    default: "main"
  - name: pr-number
    type: string
  volumes:
  - name: trusted-ca
    configMap:
      name: trusted-ca
      items:
        - key: ca-bundle.crt 
          path: tls-ca-bundle.pem
  steps:
  - name: create-webhook
    image: quay.io/openshift/origin-cli:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: user.home
      value: /tekton/home
    workingDir: "/workspace"
    script: |
      #!/bin/bash
      echo -----------------------------------
      #. /workspace/env-vars
      PROJECT_PATH=$(echo $(params.git-repo-url) | cut -d"/" -f4- | cut -d"." -f1)
      echo $(params.git-repo-url) | cut -d"/" -f4- | cut -d"." -f1
      echo $PROJECT_PATH
      GIT_URL=$(echo $(params.git-repo-url) | cut -d"/" -f-3) 
      echo $GIT_URL
      GIT_CREDS="$(cat /tekton/creds-secrets/gitea-secret/username):$(cat /tekton/creds-secrets/gitea-secret/password)"
      API_PATH="/api/v1/repos/${PROJECT_PATH}/hooks"
      API_URL="${GIT_URL}${API_PATH}"
      SECRET="6584092dcca6e0416972376d9c34f712"
      echo curl -k -X DELETE -u ${GIT_CREDS} -H "\"Content-Type: application/json\""  ${GIT_URL}/api/v1/repos/${PROJECT_PATH}/labels/1
      curl -k -X DELETE -u ${GIT_CREDS} -H "\"Content-Type: application/json\""  ${GIT_URL}/api/v1/repos/${PROJECT_PATH}/labels/1
      echo curl -k -X POST -u ${GIT_CREDS} -H "\"Content-Type: application/json\"" -d "\"{\"name\": \"Validated\", \"color\": \"#70c24a\", \"id\": 1}\"" ${GIT_URL}/api/v1/repos/${PROJECT_PATH}/labels
      curl -k -X POST -u ${GIT_CREDS} -H "Content-Type: application/json" -d "\"{\"name\": \"Validated\", \"color\": \"#70c24a\", \"id\": 1}\"" ${GIT_URL}/api/v1/repos/${PROJECT_PATH}/labels
      echo curl -k -X PATCH -u ${GIT_CREDS} -H "Content-Type: application/json" -d "{\"labels\": [1]}\"" ${GIT_URL}/api/v1/repos/${PROJECT_PATH}/pulls/2
      curl -k -X PATCH -u ${GIT_CREDS} -H "Content-Type: application/json" -d "\"{\"labels\": [1]}i\"" ${GIT_URL}/api/v1/repos/${PROJECT_PATH}/pulls/2
      echo -----------------------------------
