apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
  namespace: cicd-devsec-ops
spec:
  description: | 
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
  - name: repo-url
    type: string
  - name: image-reference
    type: string
  - name: dockerpath
    description: path to dockerfile
    type: string
  - name: pr-number
    type: string
  workspaces:
  - name: shared-data
  - name: maven-settings
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: sslVerify
      value: "false"
  - name: maven-run
    taskRef:
      name: maven
    runAfter:
      - fetch-source
    params:
      #- name: CONTEXT_DIR
      #  value: "apps/greeter/java/quarkus"
      - name: GOALS
        value:
          - -DskipTests
          - clean
          - package
    workspaces:
      - name: maven-settings
        workspace: maven-settings
      - name: source
        workspace: shared-data
  - name: build-push
    runAfter: 
      - maven-run 
    taskRef:
      name: kaniko
    workspaces:
    - name: source
      workspace: shared-data
        #  - name: dockerconfig
        #workspace: docker-credentials
    params:
    - name: IMAGE
      value: $(params.image-reference)
    - name: DOCKERFILE
      value: $(params.dockerpath)
  - name: sign-image
    params:
      - name: image
        value: $(params.image-reference)
    runAfter:
      - build-push
    taskRef:
      kind: Task
      name: cosign
        #workspaces:
        #- name: source
        #workspace: shared-data
  - name: image-check
    runAfter:
      - sign-image
    taskRef:
      name: stackrox-image-check
      kind: ClusterTask
    params:
      - name: image
        value: $(params.image-reference)
      - name: rox_api_token
        value: roxsecrets
      - name: rox_central_endpoint
        value: roxsecrets
  - name: image-scan
    runAfter:
      - image-check
    taskRef:
      name: stackrox-image-scan
      kind: ClusterTask
    params:
      - name: image
        value: $(params.image-reference)
      - name: rox_api_token
        value: roxsecrets
      - name: rox_central_endpoint
        value: roxsecrets
      - name: output_format
        value: csv
  - name: gitea-set-status
    runAfter:
      - image-scan
    params:
      - name: git-repo-url
        value: $(params.repo-url)
      - name: pr-number
        value: $(params.pr-number)
    taskRef:
      kind: ClusterTask
      name: validated-pr 

