apiVersion: v1
kind: Namespace
metadata:
  name: cicd-devsec-ops 
  annotations:
    openshift.io/node-selector: ""
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
  annotations:
    openshift.io/node-selector: ""
