apiVersion: v1
kind: Namespace
metadata:
  name: cicd-devsec-ops 
  annotations:
    openshift.io/node-selector: ""
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
  annotations:
    openshift.io/node-selector: ""
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: quay
  annotations:
    openshift.io/node-selector: ""
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
