apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-devsec-ops
  namespace: openshift-gitops
spec:
  project: cicd-devsec-ops
  source:
    repoURL: https://github.com/feven-redhat/cicd-devsec-ops.git
    targetRevision: pull-request
    path: gitops/base
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd-devsec-ops
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
