apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cicd-devsec-ops
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/feven-redhat/cicd-devsec-ops.git 
status: {}
